title: Tri-Nhu Do
logo: /img/trinhu.png
description: Postdoctoral Research Fellow  
Resilient Machine Learning Institute (ReMI)  
École de Technologie Supérieure (ÉTS)  
Université du Québec, Montreal, Canada  
Email: tri-nhu.do.1 (at) ens.etsmtl.caAcademic Profile. 
google_analytics:
theme: jekyll-theme-minimal
