title: Tri Nhu Do
logo: /images/TriNhu.jpeg
description: Postdoctoral Research Fellow
Department of Electrical Engineering
École de Technologie Supérieure (ÉTS)
Université du Québec, Montreal, Canada
theme: jekyll-theme-minimal
