title: Tri Nhu Do
logo: /images/trinhuphoto.png
description: Postdoctoral Research Fellow <br> Department of Electrical Engineering <br> École de Technologie Supérieure (ÉTS) <br> Université du Québec, Montreal, Canada
theme: jekyll-theme-minimal
font-family: Georgia
